CoreWebsite/Controllers/TestimonialController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoreWebsite.Controllers
{
    public class TestimonialController : Controller
    {
        TestimonialManager testimonialManager = new TestimonialManager(new EfTestimonialDal());
        public IActionResult Index()
        {
            var values = testimonialManager.TGetList();
            return View(values);
        }
        public IActionResult TestimonialDelete(int id)
        {
            var value = testimonialManager.TGetById(id);
            testimonialManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult TestimonialAdd()
        {

            return View();
        }
        [HttpPost]
        public IActionResult TestimonialAdd(int id)
        {
            var value = testimonialManager.TGetById(id);
            testimonialManager.TDelete(value);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult TestimonialEdit(int id)
        {
            var value = testimonialManager.TGetById(id);
      
            return View(value);
        }
        [HttpPost]
        public IActionResult TestimonialEdit(Testimonial p)
        {
          testimonialManager.TUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

CoreWebsite/Views/Testimonial/Index.cshtml
@using EntityLayer.Concrete
@model List<Testimonial>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}



<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Reference List</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                
                               
                                <th>#</th>
                     
                                <th> Company </th>
                                <th> Title </th>
                                <th> Delete Mode </th>
                                <th> Details </th>
                      
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                              
                                   

                                    <td>
                                        <img src="@item.ImageUrl" alt="image" />
                                        <span class="pl-2">@item.TestimonialName</span>
                                    </td>
                                 
                                    <td> @item.Company </td>
                                    <td> @item.Title </td>
                                    <td> <a href="/Testimonial/TestimonialDelete/@item.TestimonialID" class="btn btn-outline-danger">Delete </a> </td>
                                    <td> <a href="/Testimonial/TestimonialEdit/@item.TestimonialID" class="btn btn-outline-info">Details </a> </td>

                            </tr>
                                }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

CoreWebsite/Views/Testimonial/TestimonialEdit.cshtml
@model EntityLayer.Concrete.Testimonial
@{
    ViewData["Title"] = "TestimonialEdit";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<h1>TestimonialEdit</h1>


@using (Html.BeginForm("TestimonialEdit", "Testimonial", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Reference Details Page </h4>
                <form class="forms-sample">
                    @Html.HiddenFor(x => x.TestimonialID)
                    <div class="form-group">
                        @Html.Label("Name Surname")
                        @Html.TextBoxFor(x => x.TestimonialName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Company")
                        @Html.TextBoxFor(x => x.Company, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Title")
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("ImageUrl")
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Comment")
                        @Html.TextAreaFor(x => x.Comment, 6, 3, new { @class = "form-control" })
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Save</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>

}
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>