CoreWebsite/Controllers/ExperienceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace CoreWebsite.Controllers
{
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());
        public IActionResult Index()
        {
           
            var values = experienceManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddExperience()
        {
           

            return View();
        }
        [HttpPost]
        public IActionResult AddExperience(Experience p)
        {
            experienceManager.TAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteExperience(int id)
        {
            var value = experienceManager.TGetById(id);
            experienceManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditExperience(int id)
        {
           
            var values = experienceManager.TGetById(id);

            return View(values);
        }
        [HttpPost]
        public IActionResult EditExperience(Experience p)
        {
            experienceManager.TUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

CoreWebsite/Views/Experience/AddExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
{
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Experience Adding Page </h4>
            <form class="forms-sample">
                <div class="form-group">
                        @Html.Label("Name")
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                        @Html.Label("Date")
                        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                </div>
                <div class="form-group">
                        @Html.Label("ImageUrl")
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                </div>
                    <div class="form-group">
                        @Html.Label("Description")
                        @Html.TextAreaFor(x => x.Description, 6, 3, new { @class = "form-control" })
                    </div>

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-dark">Cancel</button>
            </form>
        </div>
    </div>
</div>

}
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>

CoreWebsite/Views/Experience/EditExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "EditExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Experience Editing Page </h4>
                <form class="forms-sample">
                    @Html.HiddenFor(x => x.ExperienceID)
                    <div class="form-group">
                        @Html.Label("Name")
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Date")
                        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("ImageUrl")
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Description")
                        @Html.TextAreaFor(x => x.Description,6,3, new { @class = "form-control" })
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>

}
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>

CoreWebsite/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}



<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Experience List Table</h4>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Date</th>
                            <th>ImageUrl</th>
                            <th>Description</th>
                            <th>Delete</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td> @item.ExperienceID</td>

                                <td> @item.Name  </td>

                                <td> @item.Date</td>
                                <td> @item.ImageUrl</td>
                                <td> @item.Description</td>
                                <td><a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-danger">DELETE</a></td>
                                <td><a href="/Experience/EditExperience/@item.ExperienceID" class="btn btn-info">EDIT</a></td>


                            </tr>
                        }
                    </tbody>
                </table>
               
            </div>
        </div>
    </div>
</div>
<a href="/Experience/AddExperience/" class="btn btn-primary">ADD NEW EXPERIENCE</a>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>