CoreWebsite/Controllers/SocialMediaController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace CoreWebsite.Controllers
{
    public class SocialMediaController : Controller
    {
        SocialMediaManager socialMediaManager = new SocialMediaManager(new EfSocialMediaDal());
        public IActionResult Index()
        {
            var values = socialMediaManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult DeleteSocialMedia(int id)
        {
            var value = socialMediaManager.TGetById(id);
            socialMediaManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditSocialMedia(int id)
        {
            var value = socialMediaManager.TGetById(id);
            return View(value);
        }
        [HttpPost]
        public IActionResult EditSocialMedia(SocialMedia p)
        {
            p.Icon = " ";
            p.Status = true;
            socialMediaManager.TUpdate(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddSocialMedia()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSocialMedia(SocialMedia p)
        {
            p.Status = true;
            p.Icon = " ";
            socialMediaManager.TAdd(p);
            return RedirectToAction("Index");
        }
    }
}

CoreWebsite/Views/SocialMedia/AddSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia
@{
    ViewData["Title"] = "AddSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}



@using (Html.BeginForm("AddSocialMedia", "SocialMedia", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">SocialMedia Adding Page </h4>
                <form class="forms-sample">
                    <div class="form-group">
                        @Html.Label("SociaMedia")
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Url")
                        @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>

}

CoreWebsite/Views/SocialMedia/EditSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia
@{
    ViewData["Title"] = "EditSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("EditSocialMedia", "SocialMedia", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">SocialMedia Editing Page </h4>
                <form class="forms-sample">
                    @Html.HiddenFor(x => x.SocialMediaID)
                    <div class="form-group">

                        @Html.Label("SocialMedia")
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">

                        @Html.Label("Url")
                        @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
                    </div>


                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>

CoreWebsite/Views/SocialMedia/Index.cshtml
@using EntityLayer.Concrete
@model List<SocialMedia>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}



<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Socialmedia List </h4>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>SocialMedia</th>
                            <th>Url</th>
                            <th>Delete</th>
                            <th>Edit</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <th>
                                   
                                   @item.SocialMediaID
                                  
                                </th>
                                <td class="budget">
                                    @item.Name
                                </td>
                                <td> <a href="@item.Url" >@item.Url</a></td>
                          
                                
                                <td><a href="/SocialMedia/DeleteSocialMedia/@item.SocialMediaID" class="btn btn-danger">DELETE</a></td>
                                <td><a href="/SocialMedia/EditSocialMedia/@item.SocialMediaID" class="btn btn-info">EDIT</a></td>
                              

                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
<a href="/SocialMedia/AddSocialMedia/" class="btn btn-primary">Add New SocialMedia</a>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>